---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.5
services:
  - postgresql
before_install: gem install bundler -v 1.17.1
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
